export type {
  PostDTO,
  PostDetailedDTO,
  PostTextDTO,
  PostTagDTO,
  PostPhotoDTO,
  PostVideoDTO,
  PostLocationDTO,
  PostSurveyDTO,
  PostAuthorDTO,
  SurveyAnswerDTO,
  GetPostsRequestDTO,
  GetPostsResponseDTO,
  GetPostRequestDTO,
  GetPostResponseDTO,
  CreatePostRequestDTO,
  CreatePostResponseDTO,
  PatchPostRequestDTO,
  PatchPostResponseDTO,
  DeletePostRequestDTO,
  DeletePostResponseDTO,
  PaginationMetaDTO,
  PostStatusDTO,
  PostTypeDTO,
  PostLocationTypeDTO,
  SurveyTypeDTO,
  PostAuthorTypeDTO,
} from '@shared-types';
